version: 2.1
orbs:
  matlab: mathworks/matlab@dev:alpha
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - matlab/install
      - matlab/run-tests:
          test-results-junit: test-results/matlab/results.xml
          code-coverage-cobertura: code-coverage/coverage.xml
          code-coverage-source: sources
      - store_test_results:
          path: test-results
      - codecov/upload:
          file: code-coverage/coverage.xml
