version: 2.1
orbs:
  matlab: mathworks/matlab@dev:alpha
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - matlab/install
      - matlab/run-tests:
          test-results-junit: test-results/matlab/results.xml
          code-coverage-cobertura: code-coverage/coverage.xml
          code-coverage-source: source
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: code-coverage